### ISSUE TITLE
`0 is false` is false

### ISSUE THREAD

**Issue by bawejakunal** [akshaynagpal/go-home-at-five#2]
In kernel level coding by convention 0 indicates a successful return from a function and a non-zero value is used to indicate an error. However, its true that in most programming languages 0 translates to a `boolean false` or equivalent. I think the word `boolean` should be specified here to stress on that :)

**Comment by akshaynagpal** [comment]
Thanks a lot! A PR will be appreciated. Else, I will edit it soon! 👍

**Comment by akshaynagpal** [comment]
Done in commit https://github.com/akshaynagpal/go-home-at-five/commit/5a063184c44c3485bc289f9421d471ad2a99189d 
Your name is now in the contributors at https://github.com/akshaynagpal/go-home-at-five/blob/master/CONTRIBUTING.md 🥇
